### ISSUE TITLE
Unable to Run the AuthenticationFlowExampleTest.java

### ISSUE THREAD

**Issue by sureshcankado** [oviva-ag/ehealthid-relying-party#90]
com.oviva.ehealthid.fedclient.api.HttpException: http request failed: bad status 'GET https://gsi-ref.dev.gematik.solutions/.well-known/openid-federation' status=403
	at com.oviva.ehealthid.fedclient.api.HttpExceptions.httpFailBadStatus(HttpExceptions.java:10)
	at com.oviva.ehealthid.fedclient.api.FederationApiClientImpl.doGetRequest(FederationApiClientImpl.java:74)
	at com.oviva.ehealthid.fedclient.api.FederationApiClientImpl.fetchEntityConfiguration(FederationApiClientImpl.java:54)
	at com.oviva.ehealthid.fedclient.api.CachedFederationApiClient.lambda$2(CachedFederationApiClient.java:47)
	at com.oviva.ehealthid.fedclient.api.InMemoryCacheImpl.lambda$0(InMemoryCacheImpl.java:29)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
	at com.oviva.ehealthid.fedclient.api.InMemoryCacheImpl.computeIfAbsent(InMemoryCacheImpl.java:23)
	at com.oviva.ehealthid.fedclient.api.CachedFederationApiClient.fetchEntityConfiguration(CachedFederationApiClient.java:46)
	at com.oviva.ehealthid.fedclient.FederationMasterClientImpl.fetchTrustedEntityConfiguration(FederationMasterClientImpl.java:51)
	at com.oviva.ehealthid.fedclient.FederationMasterClientImpl.establishIdpTrust(FederationMasterClientImpl.java:46)
	at com.oviva.ehealthid.auth.internal.steps.SelectSectoralIdpStepImpl.redirectToSectoralIdp(SelectSectoralIdpStepImpl.java:66)
	at com.oviva.ehealthid.auth.AuthenticationFlowExampleTest.flowIntegrationTest(AuthenticationFlowExampleTest.java:100)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

**Comment by thomasrichner-oviva** [comment]
Please provide proper context.
