### ISSUE TITLE
Status Code mismatch in doFederatedAuthFlow function

### ISSUE THREAD

**Issue by sureshcankado** [oviva-ag/ehealthid-relying-party#93]
Hello Thomas, 

var fedmaster = URI.create("https://app-ref.federationmaster.de");
var self = URI.create("https://diga.cankado.com");

 // this URI must be listed in your entity statement, configure as needed
 var redirectUri = URI.create("https://diga.cankado.com/auth/callback");

// those _MUST_ be at most the ones you requested when handing in the entity statement
var scopes = List.of("openid");
var sektoralerIdpIss = "https://gsi-ref.dev.gematik.solutions";

I was able to fix the configuration issues and now the error has changed to 

org.opentest4j.AssertionFailedError: response was:
(GET https://gsi-ref.dev.gematik.solutions/auth?request_uri=urn%3Ahttps%3A%2F%2Fdiga.cankado.com%3Ab1772942c5011653&user_id=) 400 ==> expected: <302> but was: <400>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:563)
	at com.oviva.ehealthid.auth.AuthenticationFlowExampleTest.doFederatedAuthFlow(AuthenticationFlowExampleTest.java:161)
	at com.oviva.ehealthid.auth.AuthenticationFlowExampleTest.flowIntegrationTest(AuthenticationFlowExampleTest.java:105)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

it seems user_id is blank , but dont know why

**Comment by sureshcankado** [comment]
Hello Thomas, 

I tried to do a quick fix the above error by adding a test kvnr value as follows

var formSubmit = action + "?" + new String(urlEncoded, StandardCharsets.UTF_8) + "X110536543";

then the api call was 302 and that code worked and in next step 

// ==== 4) exchange the code for the ID token
var token = step2.exchangeSectoralIdpCode(code, verifier);

here it raised an error 
java.lang.IllegalArgumentException: The private key (JWK) must not be null
	at com.nimbusds.jose.crypto.MultiDecrypter.<init>(MultiDecrypter.java:178)
	at com.nimbusds.jose.crypto.MultiDecrypter.<init>(MultiDecrypter.java:155)
	at com.oviva.ehealthid.auth.internal.steps.TrustedSectoralIdpStepImpl.exchangeSectoralIdpCode(TrustedSectoralIdpStepImpl.java:71)
	at com.oviva.ehealthid.auth.AuthenticationFlowExampleTest.flowIntegrationTest(AuthenticationFlowExampleTest.java:113)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

Generated jwe object is given below

jweObject.getHeaders() = {"epk":{"kty":"EC","crv":"P-256","x":"Z3r7gM3IUvh36vZ7-QUoYL62lwLj6LDniA8-Dtb62V0","y":"RTZgD4eDYgFd6kn1S4qnFO-ex4O6LNvUARmqm6Vb-Vc"},"kid":"v1838Rx-Fvxjfp6rmQgjRPr9wdJo4v2dBv6_NBbq_z4","cty":"JWT","enc":"A256GCM","alg":"ECDH-ES"}

relyingPartyEncKeySupplier.apply(jweObject.getHeader().getKeyID()); this code is returning null

**Comment by henryallsuch** [comment]
I am also getting this issue in my test, I see the label has been added as `invalid`.  What was the resolution? @sureshcankado
